<a href="https://colab.research.google.com/github/RayaRavi/Data-Mining-/blob/main/DM_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


In [ ]:
import pandas as pd
data = pd.read_excel('/content/data1.csv.xlsx')
print(data)

    id       name  maths  physics
0    1      munny     30       30
1    2       siri     22       24
2    3  varshitha     24       23
3    4     taruni     25       21
4    5    meghana     26       23
5    6   prasanna     27       24
6    7    shrihan     28       25
7    8    revanth     29       26
8    9      rohit     30       26
9   10    keerthi     24       27
10  11     shahin     14       28
11  12      honey     15       29
12  13       janu     16       30
13  14     varshi     17       23
14  15    chanbee     15       22
15  16      rehan     28       21
16  17    rasheed     20       20
17  18   gayathri     22       24
18  19      manju     23       25
19  20       rama     24       26


In [ ]:
import pandas as pd
d=pd.read_csv('/content/BIKE DETAILS.csv')
print(d)

                                     name  selling_price  year seller_type  \
0               Royal Enfield Classic 350         175000  2019  Individual   
1                               Honda Dio          45000  2017  Individual   
2     Royal Enfield Classic Gunmetal Grey         150000  2018  Individual   
3       Yamaha Fazer FI V 2.0 [2016-2018]          65000  2015  Individual   
4                   Yamaha SZ [2013-2014]          20000  2011  Individual   
...                                   ...            ...   ...         ...   
1056                            Activa 3g          17000  2010  Individual   
1057                     Honda CB twister          16000  2012  Individual   
1058                   Bajaj Discover 125          15000  2013  Individual   
1059                       Honda CB Shine          12000  2009  Individual   
1060                     Bajaj Pulsar 150          10000  2008  Individual   

          owner  km_driven  ex_showroom_price  
0     1st owner

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv('/content/Data.csv')
print("-------------THIS IS THE DATA IN THE FILE-------------")
print(data)
a=data.head()
b=data.tail()
print("-------------THIS IS THE DATA OF HEAD() IN DATA---------")
print(a)
print("-------------THIS IS THE DATA OF TAIL() IN DATA---------")
print(b)
data.shape

-------------THIS IS THE DATA IN THE FILE-------------
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
-------------THIS IS THE DATA OF HEAD() IN DATA---------
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
-------------THIS IS THE DATA OF TAIL() IN DATA---------
   Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


(10, 4)

In [ ]:
x=data.iloc[:,:]
print("-----------THE VARIABLES IN THE GIVEN DATASET-----------------")
print(x)

-----------THE VARIABLES IN THE GIVEN DATASET-----------------
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
x=data.iloc[:,0:3]
print("-----------THE VARIABLES IN THE GIVEN DATASET WITH SPECIFIC COLUMNS-----------------")
print(x)

-----------THE VARIABLES IN THE GIVEN DATASET WITH SPECIFIC COLUMNS-----------------
   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


In [ ]:
x=data.iloc[:,:-1]
print("-----------THE INDEPENDENT VARIABLES IN THE GIVEN DATASET-----------------")
print(x)

-----------THE INDEPENDENT VARIABLES IN THE GIVEN DATASET-----------------
   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


In [ ]:
x=data.iloc[:,-1:]
print("-----------THE DEPENDENT VARIABLES IN THE GIVEN DATASET-----------------")
print(x)

-----------THE DEPENDENT VARIABLES IN THE GIVEN DATASET-----------------
  Purchased
0        No
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No
7       Yes
8        No
9       Yes


In [ ]:
y=data.iloc[:,-1:].values
print("-----------THE DEPENDENT VARIABLES IN THE GIVEN DATASET-----------------")
print(y)

-----------THE DEPENDENT VARIABLES IN THE GIVEN DATASET-----------------
[['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['Yes']]


In [ ]:
a=data.Age.mean()
b=data.Salary.mean()
print(b)
print(a)

63777.77777777778
38.77777777777778


In [10]:
from sklearn.impute import SimpleImputer
x=data.iloc[:,:-1].values
imputer = SimpleImputer(missing_values = np.NaN, strategy = 'mean')
imputer = imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
x=data[['Country','Age','Salary']]
print(x)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


In [ ]:
y=data['Purchased']
print(y)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


In [ ]:
from sklearn.impute import SimpleImputer
x=data.iloc[:,:-1].values
imputer = SimpleImputer(missing_values = np.NaN, strategy = 'mean')
imputer = imputer.fit(data[['Age']])
data[['Age']] = imputer.transform(data[['Age']])
imputer = imputer.fit(data[['Salary']])
data[['Salary']] = imputer.transform(data[['Salary']])
print(data)

   Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes


In [ ]:
data.isnull()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False   False      False
5    False  False   False      False
6    False  False   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [7]:
import pandas as pd
d=pd.read_csv('/content/Data1.csv')
print(d)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
d.isnull()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [ ]:
d.fillna(value=0)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      0.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   0.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
d.fillna({'Age':'young'})

Country    Age   Salary Purchased
0   France   44.0  72000.0        No
1    Spain   27.0  48000.0       Yes
2  Germany   30.0  54000.0        No
3    Spain   38.0  61000.0        No
4  Germany   40.0      NaN       Yes
5   France   35.0  58000.0       Yes
6    Spain  young  52000.0        No
7   France   48.0  79000.0       Yes
8  Germany   50.0  83000.0        No
9   France   37.0  67000.0       Yes

In [ ]:
d.fillna({'Salary':63777.777778})

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain   NaN  52000.000000        No
7   France  48.0  79000.000000       Yes
8  Germany  50.0  83000.000000        No
9   France  37.0  67000.000000       Yes

In [8]:
d.fillna(value=d['Age'].mean())
d.fillna(value=d['Salary'].max())

Country      Age   Salary Purchased
0   France     44.0  72000.0        No
1    Spain     27.0  48000.0       Yes
2  Germany     30.0  54000.0        No
3    Spain     38.0  61000.0        No
4  Germany     40.0  83000.0       Yes
5   France     35.0  58000.0       Yes
6    Spain  83000.0  52000.0        No
7   France     48.0  79000.0       Yes
8  Germany     50.0  83000.0        No
9   France     37.0  67000.0       Yes

In [13]:
import pandas as pd
pd.get_dummies(data,prefix=["AgeCatagory"],columns=["Age"])

Country   Salary Purchased  AgeCatagory_27.0  AgeCatagory_30.0  \
0   France  72000.0        No                 0                 0   
1    Spain  48000.0       Yes                 1                 0   
2  Germany  54000.0        No                 0                 1   
3    Spain  61000.0        No                 0                 0   
4  Germany      NaN       Yes                 0                 0   
5   France  58000.0       Yes                 0                 0   
6    Spain  52000.0        No                 0                 0   
7   France  79000.0       Yes                 0                 0   
8  Germany  83000.0        No                 0                 0   
9   France  67000.0       Yes                 0                 0   

   AgeCatagory_35.0  AgeCatagory_37.0  AgeCatagory_38.0  AgeCatagory_40.0  \
0                 0                 0                 0                 0   
1                 0                 0                 0                 0   
2                 0                 0                 0                 0   
3                 0                 0                 1                 0   
4                 0                 0                 0                 1   
5                 1                 0                 0                 0   
6                 0                 0                 0                 0   
7                 0                 0                 0                 0   
8                 0                 0                 0                 0   
9                 0                 1                 0                 0   

   AgeCatagory_44.0  AgeCatagory_48.0  AgeCatagory_50.0  
0                 1                 0                 0  
1                 0                 0                 0  
2                 0                 0                 0  
3                 0                 0                 0  
4                 0                 0                 0  
5                 0                 0                 0  
6                 0                 0                 0  
7                 0                 1                 0  
8                 0                 0                 1  
9                 0                 0                 0

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [18]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
x[:,0]=label.fit_transform(x[:,0])
print(x)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [21]:
from sklearn.preprocessing import OneHotEncoder
print("-------------PROCESS OF ELIMINATING OR ENCODING DUMMY VALUES-------------\n")
dummy=pd.get_dummies(data['Country'])
print(dummy)

-------------PROCESS OF ELIMINATING OR ENCODING DUMMY VALUES-------------

   France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       0        1      0
9       1        0      0


In [22]:
from sklearn.preprocessing import OneHotEncoder
print("-------------PROCESS OF ELIMINATING OR ENCODING DUMMY VALUES-------------\n")
dummy=pd.get_dummies(data['Purchased'])
print(dummy)

-------------PROCESS OF ELIMINATING OR ENCODING DUMMY VALUES-------------

   No  Yes
0   1    0
1   0    1
2   1    0
3   1    0
4   0    1
5   0    1
6   1    0
7   0    1
8   1    0
9   0    1


In [24]:
from sklearn.preprocessing import OneHotEncoder
print("-------------PROCESS OF ELIMINATING OR ENCODING DUMMY VALUES USING OneHotEncoder WITHOUT USING pandas-------------\n")
onehot=OneHotEncoder()
onehot.fit_transform(data.Country.values.reshape(-1,1)).toarray()
#print(onehot)

-------------PROCESS OF ELIMINATING OR ENCODING DUMMY VALUES-------------



array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])